---
sudo: required
# docker is required to run tests
services: docker

install:
  - bundle install

script:
  # run kitchen tests (destroy, create, converge, setup, verify and destroy)
  - bundle exec kitchen test

notifications:
  slack:
    secure: cUG63tELjDrMwugbSQH8nnaRFtVKHWdOUONAN7LIexUtqssVajmIprWIia/y6VPjICxw+q9Pxjmb3apAid1QKxbqumd+v0xZbWjSLaIJ31YL2HOfz3cota6u1kECZmstqLqwr771zUhgJRwfCBSpOInDDK4G1qVd/Mu4JND7gScYV/zgZ5MTi09J17JjPGUS9UHFo3ZzMfd7LCxkPgh3lcS1cFfiamjHrfz6YtpiieBEBfpwugBEBkazdAIuiAeHmP3Ogk3vphJQ4h4lG8884BdTtnNMvDhl7AWmnIMqKbPDIYe/0IR7O3cxRoUPuHSEi8+GgRlMGCBExh9Em/vaYx1XBR5Tgx9yX0JrY4i6iGHQ1JqDv+jrifjB80fUhuKE3MqGDvkRK3fMwDOEpdTcr2JuaOx0M6ctUt6EmQwdru1vo4ySDFNGZfMGiWzxguqdgccQHmBfPLqrTGwi5khxegFzbWIKjfzPebZlDUoaZ4TvEXpMA7tbKVTOTovpleXs8NnzmP5taNoR3sIgrp6Beqm/a/Z8zN6OLgT7nBNZBI5g65nqUscKamwmtUe9YC0olPXCwFUp3BqEA040f9PPWPI3CtY0OIOMeFisHvyr9WOhGRlNstJ9CxEgnsYH+rHT2q0g4KCGfwCFOWLlS7MRRxYdG/9iEjeBnGJbag1nmKo=
