---
- name: Install Packages | apt | build dependencies
  apt:
    state: latest
    name: "{{ item }}"
  with_items: '{{ python_build_dependencies }}'
  when: python_build_dependencies
  tags:
    - software-installation
    - using-apt
    - python

- name: Install Packages | apt
  apt:
    state: latest
    name: "{{ item }}"
  with_items:
    - python-dev
    - python-setuptools
    - python-pip
    - python3
    - python3-dev
    - python3-setuptools
    - python3-pip
  tags:
    - software-installation
    - using-apt
    - python

- name: "Install Packages | pip | {{ python_packages }}"
  pip:
    executable: "{{ python_pip_executable }}"
    state: latest
    name: "{{ item }}"
<<<<<<< HEAD
  with_items: '{{ python_packages }}'
=======
  with_items: "{{ python_packages }}"
>>>>>>> ad4a9c1a89decf1e3e6039acb7df1e059ca0e824
  when: python_packages
  tags:
    - software-installation
    - using-pip
    - python

- name: Install Packages | pip | requirements file
  pip:
    executable: "{{ python_pip_executable }}"
    state: latest
    requirements: "{{ python_requirements_file }}"
  when: python_requirements_file != 'omit'
  tags:
    - software-installation
    - using-pip
    - python
