---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - python-dev
    - python-setuptools
  when: python_legacy_support
  tags:
    - software-installation
    - using-apt
    - legacy-support
    - python

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - python3
    - python3-setuptools
    - python3-dev
  when: not python_legacy_support
  tags:
    - software-installation
    - using-apt
    - python

- name: Install Packages | easy_install
  easy_install:
    executable: "{{ python_easy_install_executable }}"
    name: pip
  tags:
    - software-installation
    - using-easy_install
    - python

- name: Install Packages | pip
  pip:
    executable: "{{ python_pip_executable }}"
    state: latest
    name: "{{ item }}"
    requirements: "{{ python_requirements_file | default(omit) }}"
  with_items: python_packages
  when: python_packages is iterable
  tags:
    - software-installation
    - using-pip
    - python
